extends Node

# needs some changes
# (potentially autogenerated with an editor script?)

enum {
	TOP,
	BOTTOM,
	NORTH,
	SOUTH,
	EAST,
	WEST,
	SOLID
}

"""enum {
	AIR,
	GRASS,
	DIRT,
	STONE,
	TURF,
	PLATE
}"""

"""const block_types = {
	AIR:{
		SOLID:false
	},
	GRASS:{
		TOP:Vector2(0,0), BOTTOM:Vector2(2,0),
		NORTH:Vector2(1,0), SOUTH:Vector2(1,0),
		EAST:Vector2(1,0), WEST:Vector2(1,0),
		SOLID:true
	},
	DIRT:{
		TOP:Vector2(2,0), BOTTOM:Vector2(2,0),
		NORTH:Vector2(2,0), SOUTH:Vector2(2,0),
		EAST:Vector2(2,0), WEST:Vector2(2,0),
		SOLID:true
	},
	STONE:{
		TOP:Vector2(3,0), BOTTOM:Vector2(3,0),
		NORTH:Vector2(3,0), SOUTH:Vector2(3,0),
		EAST:Vector2(3,0), WEST:Vector2(3,0),
		SOLID:true
	},
	TURF:{
		TOP:Vector2(0,1), BOTTOM:Vector2(3,1),
		NORTH:Vector2(1,1), SOUTH:Vector2(1,1),
		EAST:Vector2(1,1), WEST:Vector2(1,1),
		SOLID:true
	},
	PLATE:{
		TOP:Vector2(2,1), BOTTOM:Vector2(2,1),
		NORTH:Vector2(2,1), SOUTH:Vector2(2,1),
		EAST:Vector2(2,1), WEST:Vector2(2,1),
		SOLID:true
	}
}"""
